### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by Cobwebster** [OneSignal/OneSignal-ChromeApp-SDK#2]
So we've managed to setup onesignal fine, however when people run my extension they need to manually disable then re-enable the extension for oneSignal to generate a Onesingal playerID. Once they've done that it works perfectly.

Just wondering why google chromes initial load wouldn't trigger a creation of subscription?

**Comment by jkasten2** [comment]
@Cobwebster In testing I wasn't able to reproduce an issue where the Chrome Extension would not subscribe to OneSignal. If you check the "All Users" page on the OneSignal dashboard you should see your device show up right away.

However an issue with `OneSignal.getIdsAvailable` was discovered where it won't fire if it is called before the SDK was done registering. This is something we are looking into fixing.

Let us know if the above is differs than what you are seeing.
